In [27]:
import pandas as pd

employees = pd.DataFrame({
    "employee_id": [1,2,3,4,5,6,7,8,9,10],
    "name":        ["Alice","Bob","Charlie","Diana","Eve",
                    "Frank","Grace","Henry","Isla","Jack"],
    "department":  ["Sales","Engineering","Sales","HR","Engineering",
                    "Sales","HR","Engineering","Sales","HR"],
    "hire_date":   ["2020-03-15","2019-07-20","2021-01-10","2018-11-05",
                    "2022-06-30","2020-09-14","2019-03-22","2023-01-15",
                    "2021-08-10","2022-04-05"]
})

performance = pd.DataFrame({
    "review_id":   list(range(1,16)),
    "employee_id": [1,2,3,4,5,6,7,8,9,10,1,3,5,7,9],
    "score":       [85,92,78,88,95,72,80,91,76,84,90,82,88,75,79],
    "bonus":       [500,800,400,600,1000,300,450,750,350,550,600,500,900,400,400],
    "review_date": ["2024-01-10","2024-01-15","2024-01-20","2024-02-01",
                    "2024-02-10","2024-02-15","2024-02-20","2024-03-01",
                    "2024-03-10","2024-03-15","2024-03-20","2024-04-01",
                    "2024-04-10","2024-04-15","2024-04-20"]
})

def employee_performance(employees, performance):
    # Step 1: Convert hire_date and review_date to datetime
    employees['hire_date'] = pd.to_datetime(employees['hire_date'], format="%Y-%m-%d")
    performance['review_date'] = pd.to_datetime(performance['review_date'], format="%Y-%m-%d")
    
    # Step 2: Calculate average score per employee
    average_score_per_employee = performance.groupby("employee_id")["score"].mean()
    
    # Step 3: Calculate total bonus per employee
    total_bonus_per_employee = performance.groupby("employee_id")["bonus"].sum()
    
    # Step 4: Merge employees with avg score and total bonus
    merge = pd.merge(employees, average_score_per_employee, on = "employee_id", how = "left")
    merged = pd.merge(merge, total_bonus_per_employee, on = "employee_id", how = "left")
    merged = merged.rename(columns={
        "score" : "avg_score",
        "bonus" : "total_bonus"
    })
    
    # Step 5: Add a column 'rating':
    # 'Top Performer'    — avg score >= 88
    # 'Solid Performer'  — avg score between 75 and 88
    # 'Needs Improvement'— avg score < 75
    import numpy as np
    conditions = [
        merged["avg_score"]>=88,
        (merged["avg_score"]>=75) & (merged["avg_score"]<88),
        merged["avg_score"]<75
    ]
    choices = ["Top Performer", "Solid Performer", "Needs Improvement"]
    merged["rating"] = np.select(conditions, choices, default="Needs Improvement")
        
    # Step 6: Count employees per rating
    Count_employees_per_rating = merged.groupby("rating")["employee_id"].count()
    
    # Step 7: Average bonus per department
    Average_bonus_per_department = merged.groupby("department")["total_bonus"].mean()

    # Step 8: Return summary dict with keys:
    # 'top_performer', 'rating_counts', 'avg_bonus_by_dept'
    # top_performer = name of employee with highest avg score
    name_highest_avg_score = merged.groupby("name")["avg_score"].sum()
    name_highest_avg_score.idxmax()
    summary = {
        'top_performer':name_highest_avg_score.idxmax(),
        'rating_counts': Count_employees_per_rating,
        'avg_bonus_by_dept': Average_bonus_per_department
    }
    
    return summary

print(employee_performance(employees, performance))

{'top_performer': 'Bob', 'rating_counts': rating
Needs Improvement    1
Solid Performer      5
Top Performer        4
Name: employee_id, dtype: int64, 'avg_bonus_by_dept': department
Engineering    1150.000000
HR              666.666667
Sales           762.500000
Name: total_bonus, dtype: float64}

In [4]:
import pandas as pd

import pandas as pd

employees = pd.DataFrame({
    "employee_id": [1,2,3,4,5,6,7,8,9,10],
    "name":        ["Alice","Bob","Charlie","Diana","Eve",
                    "Frank","Grace","Henry","Isla","Jack"],
    "department":  ["Sales","Engineering","Sales","HR","Engineering",
                    "Sales","HR","Engineering","Sales","HR"],
    "hire_date":   ["2020-03-15","2019-07-20","2021-01-10","2018-11-05",
                    "2022-06-30","2020-09-14","2019-03-22","2023-01-15",
                    "2021-08-10","2022-04-05"]
})

performance = pd.DataFrame({
    "review_id":   list(range(1,16)),
    "employee_id": [1,2,3,4,5,6,7,8,9,10,1,3,5,7,9],
    "score":       [85,92,78,88,95,72,80,91,76,84,90,82,88,75,79],
    "bonus":       [500,800,400,600,1000,300,450,750,350,550,600,500,900,400,400],
    "review_date": ["2024-01-10","2024-01-15","2024-01-20","2024-02-01",
                    "2024-02-10","2024-02-15","2024-02-20","2024-03-01",
                    "2024-03-10","2024-03-15","2024-03-20","2024-04-01",
                    "2024-04-10","2024-04-15","2024-04-20"]
})


employees['hire_date'] = pd.to_datetime(employees['hire_date'], format="%Y-%m-%d")
performance['review_date'] = pd.to_datetime(performance['review_date'], format="%Y-%m-%d")

In [22]:
 # Step 2: Calculate average score per employee
average_score_per_employee = performance.groupby("employee_id")["score"].mean()
average_score_per_employee

employee_id
1     87.5
2     92.0
3     80.0
4     88.0
5     91.5
6     72.0
7     77.5
8     91.0
9     77.5
10    84.0
Name: score, dtype: float64

In [6]:
# Step 3: Calculate total bonus per employee

total_bonus_per_employee = performance.groupby("employee_id")["bonus"].sum()
total_bonus_per_employee

employee_id
1     1100
2      800
3      900
4      600
5     1900
6      300
7      850
8      750
9      750
10     550
Name: bonus, dtype: int64

In [10]:
# Step 4: Merge employees with avg score and total bonus
merge = pd.merge(employees, average_score_per_employee, on = "employee_id", how = "left")
merged = pd.merge(merge, total_bonus_per_employee, on = "employee_id", how = "left")
merged = merged.rename(columns={
    "score" : "avg_score",
    "bonus" : "total_bonus"
})
merged.head()

   employee_id     name   department  hire_date  avg_score  total_bonus
0            1    Alice        Sales 2020-03-15       87.5         1100
1            2      Bob  Engineering 2019-07-20       92.0          800
2            3  Charlie        Sales 2021-01-10       80.0          900
3            4    Diana           HR 2018-11-05       88.0          600
4            5      Eve  Engineering 2022-06-30       91.5         1900

In [12]:
# Step 5: Add a column 'rating':
    # 'Top Performer'    — avg score >= 88
    # 'Solid Performer'  — avg score between 75 and 88
    # 'Needs Improvement'— avg score < 75
import numpy as np
conditions = [
    merged["avg_score"]>=88,
    (merged["avg_score"]>=75) & (merged["avg_score"]<88),
    merged["avg_score"]<75
]
choices = ["Top Performer", "Solid Performer", "Needs Improvement"]

merged["rating"] = np.select(conditions, choices, default="Needs Improvement")

merged.head()

,employee_id,name,department,hire_date,avg_score,total_bonus,rating
0,1,Alice,Sales,2020-03-15,87.5,1100,Solid Performer
1,2,Bob,Engineering,2019-07-20,92.0,800,Top Performer
2,3,Charlie,Sales,2021-01-10,80.0,900,Solid Performer
3,4,Diana,HR,2018-11-05,88.0,600,Top Performer
4,5,Eve,Engineering,2022-06-30,91.5,1900,Top Performer

In [ ]:
 # Step 6: Count employees per rating

Count_employees_per_rating = merged.groupby("rating")["employee_id"].count()
Count_employees_per_rating

'Solid Performer'

In [16]:
#Step 7: Average bonus per department
Average_bonus_per_department = merged.groupby("department")["total_bonus"].mean()

In [17]:
Average_bonus_per_department

department
Engineering    1150.000000
HR              666.666667
Sales           762.500000
Name: total_bonus, dtype: float64

In [19]:
Count_employees_per_rating = merged.groupby("rating")["employee_id"].count()
Count_employees_per_rating.idxmax()

'Solid Performer'

In [28]:
name_highest_avg_score = merged.groupby("name")["avg_score"].sum()
name_highest_avg_score

name
Alice      87.5
Bob        92.0
Charlie    80.0
Diana      88.0
Eve        91.5
Frank      72.0
Grace      77.5
Henry      91.0
Isla       77.5
Jack       84.0
Name: avg_score, dtype: float64

In [29]:
merged.groupby("department")["total_bonus"].sum()

department
Engineering    3450
HR             2000
Sales          3050
Name: total_bonus, dtype: int64