## Business questions — solve in order:

- Add a new column revenue = quantity × unit_price
- Filter only completed orders
- What is the total revenue per customer for completed orders only?
- Who is the top spending customer?
- What is the most sold product by quantity?

In [ ]:
import pandas as pd

data = {
    "order_id":    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "customer":    ["Alice", "Bob", "Alice", "Charlie", "Bob", "Alice", "Diana", "Charlie", "Bob", "Diana"],
    "product":     ["Laptop", "Phone", "Tablet", "Laptop", "Laptop", "Phone", "Tablet", "Phone", "Tablet", "Laptop"],
    "category":    ["Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Electronics"],
    "quantity":    [1, 2, 1, 1, 3, 2, 1, 2, 1, 2],
    "unit_price":  [1200, 800, 450, 1200, 800, 800, 450, 800, 450, 1200],
    "order_date":  ["2024-01-15", "2024-01-20", "2024-02-10", "2024-02-14", "2024-02-20",
                    "2024-03-05", "2024-03-12", "2024-03-18", "2024-03-25", "2024-04-02"],
    "status":      ["completed", "completed", "completed", "cancelled", "completed",
                    "completed", "completed", "cancelled", "completed", "completed"]
}

df = pd.DataFrame(data)
print(df)

   order_id customer product     category  quantity  unit_price  order_date  \
0         1    Alice  Laptop  Electronics         1        1200  2024-01-15
1         2      Bob   Phone  Electronics         2         800  2024-01-20
2         3    Alice  Tablet  Electronics         1         450  2024-02-10
3         4  Charlie  Laptop  Electronics         1        1200  2024-02-14
4         5      Bob  Laptop  Electronics         3         800  2024-02-20
5         6    Alice   Phone  Electronics         2         800  2024-03-05
6         7    Diana  Tablet  Electronics         1         450  2024-03-12
7         8  Charlie   Phone  Electronics         2         800  2024-03-18
8         9      Bob  Tablet  Electronics         1         450  2024-03-25
9        10    Diana  Laptop  Electronics         2        1200  2024-04-02

      status
0  completed
1  completed
2  completed
3  cancelled
4  completed
5  completed
6  completed
7  cancelled
8  completed
9  completed

In [2]:
# Add a new column revenue = quantity × unit_price
revenue = df["quantity"] * df["unit_price"]

df["revenue"] = revenue

In [3]:
df.head()

,order_id,customer,product,category,quantity,unit_price,order_date,status,revenue
0,1,Alice,Laptop,Electronics,1,1200,2024-01-15,completed,1200
1,2,Bob,Phone,Electronics,2,800,2024-01-20,completed,1600
2,3,Alice,Tablet,Electronics,1,450,2024-02-10,completed,450
3,4,Charlie,Laptop,Electronics,1,1200,2024-02-14,cancelled,1200
4,5,Bob,Laptop,Electronics,3,800,2024-02-20,completed,2400

In [ ]:
# Filter only completed orders

completed = df[df["status"] == "completed"]
completed

,order_id,customer,product,category,quantity,unit_price,order_date,status,revenue
0,1,Alice,Laptop,Electronics,1,1200,2024-01-15,completed,1200
1,2,Bob,Phone,Electronics,2,800,2024-01-20,completed,1600
2,3,Alice,Tablet,Electronics,1,450,2024-02-10,completed,450
4,5,Bob,Laptop,Electronics,3,800,2024-02-20,completed,2400
5,6,Alice,Phone,Electronics,2,800,2024-03-05,completed,1600
6,7,Diana,Tablet,Electronics,1,450,2024-03-12,completed,450
8,9,Bob,Tablet,Electronics,1,450,2024-03-25,completed,450
9,10,Diana,Laptop,Electronics,2,1200,2024-04-02,completed,2400

In [7]:
#What is the total revenue per customer for completed orders only?
total_revenue_per_customer = completed.groupby("customer")["revenue"].sum()
total_revenue_per_customer

customer
Alice    3250
Bob      4450
Diana    2850
Name: revenue, dtype: int64

In [11]:
#Who is the top spending customer?
total_revenue_per_customer.idxmax()

'Bob'

In [19]:

#What is the most sold product by quantity?
df_max = df.groupby("product")["quantity"].sum()
df_max

product
Laptop    7
Phone     6
Tablet    3
Name: quantity, dtype: int64

In [20]:
#What is the most sold product by quantity?
df_max.idxmax()

'Laptop'

# Task 2

- Convert order_date to a proper datetime column.
- Extract the month from order_date into a new column called month
- Calculate total revenue per month
- Which month had the highest revenue?
- How many orders were placed per month?

In [21]:
print(df.dtypes)

order_id       int64
customer      object
product       object
category      object
quantity       int64
unit_price     int64
order_date    object
status        object
revenue        int64
dtype: object

### object to datetime

In [32]:
# - Convert order_date to a proper datetime column.

df["order_date"]= pd.to_datetime(df["order_date"], format="%Y-%m-%d")

In [30]:

df.head()

,order_id,customer,product,category,quantity,unit_price,order_date,status,revenue
0,1,Alice,Laptop,Electronics,1,1200,2024-01-15,completed,1200
1,2,Bob,Phone,Electronics,2,800,2024-01-20,completed,1600
2,3,Alice,Tablet,Electronics,1,450,2024-02-10,completed,450
3,4,Charlie,Laptop,Electronics,1,1200,2024-02-14,cancelled,1200
4,5,Bob,Laptop,Electronics,3,800,2024-02-20,completed,2400

In [31]:
print(df.dtypes)

order_id               int64
customer              object
product               object
category              object
quantity               int64
unit_price             int64
order_date    datetime64[ns]
status                object
revenue                int64
dtype: object

In [35]:
# - Extract the month from order_date into a new column called month
df["month"]=df["order_date"].dt.month
df.head()

,order_id,customer,product,category,quantity,unit_price,order_date,status,revenue,month
0,1,Alice,Laptop,Electronics,1,1200,2024-01-15,completed,1200,1
1,2,Bob,Phone,Electronics,2,800,2024-01-20,completed,1600,1
2,3,Alice,Tablet,Electronics,1,450,2024-02-10,completed,450,2
3,4,Charlie,Laptop,Electronics,1,1200,2024-02-14,cancelled,1200,2
4,5,Bob,Laptop,Electronics,3,800,2024-02-20,completed,2400,2

In [37]:
# - Calculate total revenue per month
total_rev = df.groupby("month")["revenue"].sum()
total_rev

month
1    2800
2    4050
3    4100
4    2400
Name: revenue, dtype: int64

In [40]:
# - Which month had the highest revenue?

total_rev.idxmax()

np.int32(3)

In [52]:
# - How many orders were placed per month?
df.groupby("month")["order_id"].count()

month
1    2
2    3
3    4
4    1
Name: order_id, dtype: int64

month
1    3
2    4
3    4
4    2
Name: quantity, dtype: int64