In [1]:
import pandas as pd

sales = pd.DataFrame({
    "sale_id":     [1,2,3,4,5,6,7,8,9,10,11,12],
    "rep_id":      [201,202,201,203,202,201,203,202,203,201,202,203],
    "region":      ["North","South","North","East","South","North",
                    "East","South","East","North","South","East"],
    "product":     ["Laptop","Phone","Laptop","Tablet","Phone","Tablet",
                    "Laptop","Laptop","Phone","Phone","Tablet","Laptop"],
    "quantity":    [2,3,1,2,4,1,3,2,1,2,1,2],
    "unit_price":  [1200,800,1200,450,800,450,1200,1200,800,800,450,1200],
    "sale_date":   ["2024-01-10","2024-01-15","2024-02-01","2024-02-14",
                    "2024-02-20","2024-03-01","2024-03-10","2024-03-15",
                    "2024-03-20","2024-04-01","2024-04-10","2024-04-15"],
    "returned":    [0,0,0,1,0,0,0,1,0,0,0,0]
})

reps = pd.DataFrame({
    "rep_id":   [201, 202, 203],
    "name":     ["Alice", "Bob", "Charlie"],
    "team":     ["Alpha", "Beta", "Alpha"]
})

def sales_performance(sales, reps):
    # Step 1: Add revenue column (quantity * unit_price)
    revenue = sales["quantity"] * sales["unit_price"]
    sales["revenue"] = revenue
    
    # Step 2: Convert sale_date to datetime, extract month
    sales["sale_date"] = pd.to_datetime(sales["sale_date"], format="%Y-%m-%d")
    sales["month"] = sales["sale_date"].dt.month
    
    # Step 3: Filter out returned sales (returned == 1)
    returned_sales = sales[sales["returned"] == 0]

    # Step 4: Merge with reps to get name and team

    merged_rep = pd.merge(returned_sales, reps, on ="rep_id", how = "left" )
    
    # Step 5: Total revenue per rep name
    total_revenue = merged_rep.groupby("name")["revenue"].sum()
    
    # Step 6: Best performing team by total revenue
    team_best = merged_rep.groupby("team")["revenue"].sum()
    best_team = team_best.idxmax()
    
    # Step 7: Monthly revenue trend — return as a Series
    revenue_series = sales.groupby("month")["revenue"].sum()
    # Step 8: Return summary dict with keys:
    # 'top_rep', 'best_team', 'monthly_trend'

    summary = {
        'top_rep':total_revenue.idxmax(), 
        'best_team':best_team, 
        'monthly_trend':revenue_series
    }
    
    return summary

print(sales_performance(sales, reps))

{'top_rep': 'Charlie', 'best_team': 'Alpha', 'monthly_trend': month
1    4800
2    5300
3    7250
4    4450
Name: revenue, dtype: int64}

In [2]:
import pandas as pd
sales = pd.DataFrame({
    "sale_id":     [1,2,3,4,5,6,7,8,9,10,11,12],
    "rep_id":      [201,202,201,203,202,201,203,202,203,201,202,203],
    "region":      ["North","South","North","East","South","North",
                    "East","South","East","North","South","East"],
    "product":     ["Laptop","Phone","Laptop","Tablet","Phone","Tablet",
                    "Laptop","Laptop","Phone","Phone","Tablet","Laptop"],
    "quantity":    [2,3,1,2,4,1,3,2,1,2,1,2],
    "unit_price":  [1200,800,1200,450,800,450,1200,1200,800,800,450,1200],
    "sale_date":   ["2024-01-10","2024-01-15","2024-02-01","2024-02-14",
                    "2024-02-20","2024-03-01","2024-03-10","2024-03-15",
                    "2024-03-20","2024-04-01","2024-04-10","2024-04-15"],
    "returned":    [0,0,0,1,0,0,0,1,0,0,0,0]
})

reps = pd.DataFrame({
    "rep_id":   [201, 202, 203],
    "name":     ["Alice", "Bob", "Charlie"],
    "team":     ["Alpha", "Beta", "Alpha"]
})

In [3]:
revenue = sales["quantity"] * sales["unit_price"]
sales["revenue"] = revenue
sales

,sale_id,rep_id,region,product,quantity,unit_price,sale_date,returned,revenue
0,1,201,North,Laptop,2,1200,2024-01-10,0,2400
1,2,202,South,Phone,3,800,2024-01-15,0,2400
2,3,201,North,Laptop,1,1200,2024-02-01,0,1200
3,4,203,East,Tablet,2,450,2024-02-14,1,900
4,5,202,South,Phone,4,800,2024-02-20,0,3200
5,6,201,North,Tablet,1,450,2024-03-01,0,450
6,7,203,East,Laptop,3,1200,2024-03-10,0,3600
7,8,202,South,Laptop,2,1200,2024-03-15,1,2400
8,9,203,East,Phone,1,800,2024-03-20,0,800
9,10,201,North,Phone,2,800,2024-04-01,0,1600
10,11,202,South,Tablet,1,450,2024-04-10,0,450
11,12,203,East,Laptop,2,1200,2024-04-15,0,2400

In [4]:
# Step 3: Filter out returned sales (returned == 1)
returned = sales[sales["returned"] == 0]
returned

,sale_id,rep_id,region,product,quantity,unit_price,sale_date,returned,revenue
0,1,201,North,Laptop,2,1200,2024-01-10,0,2400
1,2,202,South,Phone,3,800,2024-01-15,0,2400
2,3,201,North,Laptop,1,1200,2024-02-01,0,1200
4,5,202,South,Phone,4,800,2024-02-20,0,3200
5,6,201,North,Tablet,1,450,2024-03-01,0,450
6,7,203,East,Laptop,3,1200,2024-03-10,0,3600
8,9,203,East,Phone,1,800,2024-03-20,0,800
9,10,201,North,Phone,2,800,2024-04-01,0,1600
10,11,202,South,Tablet,1,450,2024-04-10,0,450
11,12,203,East,Laptop,2,1200,2024-04-15,0,2400

In [5]:
merged_rep = pd.merge(returned, reps, on ="rep_id", how = "left" )
merged_rep

,sale_id,rep_id,region,product,quantity,unit_price,sale_date,returned,revenue,name,team
0,1,201,North,Laptop,2,1200,2024-01-10,0,2400,Alice,Alpha
1,2,202,South,Phone,3,800,2024-01-15,0,2400,Bob,Beta
2,3,201,North,Laptop,1,1200,2024-02-01,0,1200,Alice,Alpha
3,5,202,South,Phone,4,800,2024-02-20,0,3200,Bob,Beta
4,6,201,North,Tablet,1,450,2024-03-01,0,450,Alice,Alpha
5,7,203,East,Laptop,3,1200,2024-03-10,0,3600,Charlie,Alpha
6,9,203,East,Phone,1,800,2024-03-20,0,800,Charlie,Alpha
7,10,201,North,Phone,2,800,2024-04-01,0,1600,Alice,Alpha
8,11,202,South,Tablet,1,450,2024-04-10,0,450,Bob,Beta
9,12,203,East,Laptop,2,1200,2024-04-15,0,2400,Charlie,Alpha

In [6]:
# Step 5: Total revenue per rep name
total_revenue = merged_rep.groupby("name")["revenue"].sum()
total_revenue

name
Alice      5650
Bob        6050
Charlie    6800
Name: revenue, dtype: int64

In [7]:
  # Step 6: Best performing team by total revenue
team_best = merged_rep.groupby("team")["revenue"].sum()
best_team = team_best.idxmax()
best_team

'Alpha'

In [8]:
#Step 7: Monthly revenue trend — return as a Series
revenue_series = sales["revenue"]
type(revenue_series)
revenue_series

0     2400
1     2400
2     1200
3      900
4     3200
5      450
6     3600
7     2400
8      800
9     1600
10     450
11    2400
Name: revenue, dtype: int64